services:
  postgres:
    image: postgres:13
    container_name: airflow-postgres
    networks:
      - mlops-network
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U airflow"]
      interval: 5s
      retries: 5
    volumes:
      - airflow_pgdata:/var/lib/postgresql/data

  mlflow:
    image: ghcr.io/mlflow/mlflow:v2.7.1
    container_name: mlflow
    networks:
      - mlops-network
    ports:
      - "5000:5000"
    volumes:
      - ./mlruns:/mlruns

  airflow-webserver:
    build: ./airflow
    image: airflow-custom:2.7.0
    container_name: airflow-webserver
    networks:
      - mlops-network
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres:5432/airflow
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__WEBSERVER__SECRET_KEY: california_housing_secret_key_123
      # ðŸ”¥ CRITICAL: This allows Jenkins to use admin:admin to trigger DAGs
      AIRFLOW__API__AUTH_BACKENDS: 'airflow.api.auth.backend.basic_auth,airflow.api.auth.backend.session'
      AIRFLOW__CORE__LOAD_EXAMPLES: "false"
    volumes:
      - ./dags:/opt/airflow/dags
      - ./data:/opt/airflow/data
      - ./models:/opt/airflow/models
    ports:
      - "8081:8080"
    command: webserver
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost:8080/health"]
      interval: 10s
      timeout: 10s
      retries: 5

  airflow-scheduler:
    image: airflow-custom:2.7.0
    container_name: airflow-scheduler
    networks:
      - mlops-network
    depends_on:
      airflow-webserver:
        condition: service_healthy
    environment:
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres:5432/airflow
    volumes:
      - ./dags:/opt/airflow/dags
      - ./models:/opt/airflow/models
    command: scheduler

  api:
    build: ./api
    container_name: inference-api
    networks:
      - mlops-network
    environment:
      MLFLOW_TRACKING_URI: http://mlflow:5000
    volumes:
      - ./api:/app
      - ./models:/app/models
    ports:
      - "8000:8000"

  jenkins:
    image: jenkins/jenkins:lts
    container_name: jenkins
    networks:
      - mlops-network
    user: root
    privileged: true
    ports:
      - "8082:8080"
    volumes:
      - ./jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
      - .:/app

networks:
  mlops-network:
    driver: bridge

volumes:
  airflow_pgdata:
